# Generated by Django 3.0.4 on 2020-04-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(blank=True, upload_to='logos/'),
        ),
    ]
