# Generated by Django 3.0.4 on 2020-04-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200414_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, default='', upload_to='mp3/'),
        ),
    ]
