# Generated by Django 3.0.3 on 2020-03-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200327_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='aritst',
            new_name='artist',
        ),
    ]
